require("movim.plugins")
vim.cmd("source ~/.config/nvim/main.vim")
require("movim.nvim-tree")
require("movim.fonts")
require("movim.autopairs")
require("movim.lsp")
require("movim.treesitter")
require("movim.toggleterm")
require("movim.cmp")
require("movim.lualine")
require("movim.bufferline")
require("movim.keybinds")
